version: 2
updates:
  # Maintain dependencies for Cargo
  - package-ecosystem: "cargo"
    directory: "/crates/archlinux" # Location of package manifest
    schedule:
      interval: "monthly"
  - package-ecosystem: "cargo"
    directory: "/crates/mirro-rs" # Location of package manifest
    schedule:
      interval: "monthly"
