[workspace]
members = [ "crates/*" ]
resolver = "2"

[workspace.dependencies]
itertools = "0.12.1"
serde = "1.0.200"
serde_json = "1.0.116"
tokio = "1.37.0"

[profile.release]
panic = "abort"
lto = true
strip = true
codegen-units = 1
