[workspace]
members = [ "crates/*" ]
resolver = "2"

[workspace.dependencies]
itertools = "0.12.0"
serde = "1.0.195"
serde_json = "1.0.111"
tokio = "1.35.1"

[profile.release]
panic = "abort"
lto = true
strip = true
codegen-units = 1
