[general]
outfile = "/home/user/example/generated-mirrors" # must not end with trailing slash
# Max number of mirrors to export
export = 50
view = "alphabetical" # alphabetical mirror-count
sort = "score" # percentage, duration, delay, score
cache-ttl = 24
url = "https://archlinux.org/mirrors/status/json/"

[filters]
countries = [ ]
age = 24
ipv6 = true
ipv4 = true
isos = true
protocols = [ "https", "http", "rsync" ]
completion-percent = 100
