# https://github.com/SpectralOps/rust-ci-release-template
name: Release

on:
  push:
    branches:
      - master

env:
  BIN_NAME: mirro-rs
  PROJECT_NAME: mirro-rs
  REPO_NAME: rtkay123/mirro-rs

jobs:
  changelog:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get Release Version
        id: release_version
        run: |
          export RELEASE_VERSION=$(git describe --abbrev=0 --tags)
          echo "Version: $RELEASE_VERSION"
          echo "::set-output name=release_version::$RELEASE_VERSION"

      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v1.1.2
        with:
          changelog_filename: CHANGELOG.md
          config_file: .github/changelog-ci-config.yaml
          release_version: ${{ steps.release_version.outputs.release_version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
